### ISSUE TITLE
React Native Bug

### ISSUE THREAD

**Issue by matheusmatos** [mckamey/countdown.js#27] opened 2018-01-31 11:12 UTC
Hi guys,

I have been using this module for a while with React Native and it works very well.

However, I had to make a simple change on the way that the module is exported.

Take a look here: https://github.com/mckamey/countdownjs/compare/master...matheusmatos:master

I'm not sure if I can send a pull request to that without cause incompatibility on the browser.

Basically, the module is an object instead of a function when imported with:

`import countdown from 'countdown'`

What do you think? Can I send a PR?

Thank you for this awesome library =)

**Comment by mckamey** [comment] 2020-05-08 04:24
Duplicate of #23. Your PR should be in now. Thanks!

**Closed as completed by mckamey** 2020-05-08 04:24 UTC
