### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by RoidosDiamond** [mckamey/countdown.js#18] opened 2017-05-18 08:05 UTC
hey
this project support react native?
can i import this function to react native project?

thanks

**Comment by radiovisual** [comment] 2017-06-29 10:26
Yes, this package is available on npm, so to use it in React Native, just install it like any other package:

```
npm install --save countdown
```

and then you can use it in your React Native project:

```js
import countdown from 'countdown';

countdown(new Date(2000, 0, 1)).toString();
//=> '11 years, 8 months, 4 days, 10 hours, 12 minutes and 43 seconds'
```

**Comment by RoidosDiamond** [comment] 2017-06-29 22:07
Thanks for the replay. I'll use it.
Btw i noticed a bug:
If i set the coundown now for 1.7 at 12:00 it missing a day. Any idea?

**Comment by radiovisual** [comment] 2017-06-29 22:50
Post the relevant code in a new issue so I can take a look

**Comment by mckamey** [comment] 2020-05-08 04:25
Duplicate of #23

**Closed as completed by mckamey** 2020-05-08 04:25 UTC
